<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */
/** @var \Hyva\Theme\ViewModel\HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsOutline::class);
?>
<div
    class="toolbar-sorter sorter flex items-center order-1 col-span-3 sm:col-span-6 md:col-span-3 lg:col-span-6 justify-end"
    x-data
>
    <label class="inline-block mr-3">
        <select
            data-role="sorter"
            name="sorter"
            class="form-select sorter-options"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Sort By')) ?>"
            :value="$store.meilisearch.state.sortBy"
            @change="$store.meilisearch.setSortBy($event.target.value)"
        >
            <template
                x-for="([orderCode, orderLabel]) in Object.entries($store.meilisearch.meilisearchConfig.availableSortBy || {})"
                :key="orderCode"
            >
                <option :value="orderCode" x-text="orderLabel"></option>
            </template>
        </select>
    </label>

    <button
        x-show="$store.meilisearch.state.isDescending"
        title="<?= $escaper->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
        type="button"
        class="action sorter-action sort-desc"
        :disabled="!$store.meilisearch.state.sortBy"
        :class="!$store.meilisearch.state.sortBy ? 'opacity-60 cursor-not-allowed' : ''"
        @click.prevent="$store.meilisearch.toggleSortDirection()"
    >
        <?= $heroicons->sortAscendingHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
    </button>
    <button
        x-show="!$store.meilisearch.state.isDescending"
        type="button"
        title="<?= $escaper->escapeHtmlAttr(__('Set Descending Direction')) ?>"
        class="action sorter-action sort-asc"
        :disabled="!$store.meilisearch.state.sortBy"
        :class="!$store.meilisearch.state.sortBy ? 'opacity-60 cursor-not-allowed' : ''"
        @click.prevent="$store.meilisearch.toggleSortDirection()"
    >
        <?= $heroicons->sortDescendingHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
    </button>
</div>
